### ISSUE TITLE
Add Device_ID to json response

### ISSUE THREAD

**Issue by ChewyChop** [numat/tripplite#11]
I am not sure how to request this as I am n00b.  But in using this WONDERFUL code for my personal use, I needed to include the device_id so I could create a URL parameter when building a python cgi-bin response webserver for the json.  This allowed me to query the json regardless of what order the json response was in.

This is the hack I used in the driver.py.  I am positive there is a better and more elegant way to do this.  I am just sharing as it was really useful to know which device was which as I have 4 devices to query.  

### Update to driver.py
```python
    def get(self):
        """Return an object containing all available data."""
        output = {}
        for category, data in structure.items():
            if 'address' in data:
                output[category] = self._read(data)
            else:
                output[category] = {}
                for subcategory, options in data.items():
                    output[category][subcategory] = self._read(options)
        output['device_id'] = self.path
        return output
```

### /usr/lib/cgi-bin/api file contents
```python
#!/usr/bin/python3
import json
import cgi
from tripplite import Battery, battery_paths

link = cgi.FieldStorage()
params = link.getvalue('path')
params = params.replace("'", "")

print("Content-Type: text/html")
print()
with Battery(params) as battery:
    print(json.dumps(battery.get(), indent=1))
```
### your instructions added to allow www-data access to HID
addgroup tripplite
echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="09ae", GROUP="tripplite"' > /etc/udev/rules.d/tripplite.rules
udevadm control --reload-rules
usermod -a -G tripplite www-data

### added entry for www-data in sudoers
%www-data    ALL = (root) NOPASSWD: /usr/lib/cgi-bin/api

### sample URL because of my limited python and development experience.  I just ended up URL encoding the path/device_id
http://localhost/cgi-bin/api?path=3-4%3A1.0

**Comment by alexrudd2** [comment]
Hi @ChewyChop, thanks for sharing your use case.  I don't quite know this code and may have to defer to my colleagues.  Before doing that, I can help you create a cleaned-up "Pull Request" that makes it easier to see what changes you're proposing.

First, click the Fork button on the top right corner of this webpage.  
<img width="145" alt="Screen Shot 2022-06-22 at 5 40 28 PM" src="https://user-images.githubusercontent.com/52292902/175166109-8cdd62b2-147f-4d81-8eb8-f87836bf4fd7.png">
This will create a copy ("fork") of all of our code (numat/tripplite) that's yours (ChewyChop/tripplite).  You can see mine [here](https://github.com/alexrudd2/tripplite). 

Next, navigate to `driver.py` on our copy (numat/tripplite) and click the Edit button on the right side.
<img width="113" alt="Screen Shot 2022-06-22 at 5 46 40 PM" src="https://user-images.githubusercontent.com/52292902/175166907-475c6cc2-a2f4-4dff-817e-41b25cdf5f5f.png">
GitHub will tell you that you're going to create changes on _your_ copy and request them to be pulled into ours.
<img width="1326" alt="Screen Shot 2022-06-22 at 5 49 10 PM" src="https://user-images.githubusercontent.com/52292902/175167179-7c66f9a2-4495-4efb-8e1c-63a8125a7b7f.png">

Make your changes, write an explanation of what they do, and then click Propose Changes.
<img width="685" alt="Screen Shot 2022-06-22 at 5 52 27 PM" src="https://user-images.githubusercontent.com/52292902/175167496-1910f88f-f717-4a47-8339-da244d391473.png">

Making it that far will open a Pull Request that makes things much easier.  Good luck.
