### ISSUE TITLE
Specify operating Python versions

### ISSUE THREAD

**Issue by alexrudd2** [numat/tripplite#14]
I should more precisely describe the list of Python versions this runs on.

@cooperlees  In 2020 you were running on `3.8`.  Is that still the case?  What version works for you now?

**Comment by cooperlees** [comment]
Running 3.11 now. Happy to help maintain this project too if you'd like since I use it ...

**Comment by alexrudd2** [comment]
Closed in https://github.com/numat/tripplite/commit/9235b928367f5ac032a3f955b7046095b5644f40

**Comment by alexrudd2** [comment]
> Running 3.11 now. Happy to help maintain this project too if you'd like since I use it ...

Sure!  I've set your commit bit.

Ideally, I'd like this to be up to the standards of our other repositories (such as [alicat](https://github.com/numat/alicat/), [watlow](https://github.com/numat/watlow), [productivity](https://github.com/numat/productivity)..) in terms of having a test suite, strict linters, and up-to-date docs.  However, I don't actually use it any more and it would be a little difficult to pull a live UPS to test on.
