### ISSUE TITLE
Add warning for 3016 TrippLites

### ISSUE THREAD

**Issue by patrickfuller** [numat/tripplite#3]
From [here](https://github.com/networkupstools/nut/issues/577), it looks like UPSs with product code 3016 are temperamental. May even have a different API not supported by this library.

We should specify what versions we support in the README and warn/error in the code if used otherwise.

**Comment by tomammon** [comment]
@patrickfuller could you give me some hints about how you discovered details about the API? I'd like to see if I can get 3016 devices working, and if I can, would like to contribute code to your tool to support it.

**Comment by patrickfuller** [comment]
@tomammon I emailed TrippLite customer service and got [this pdf](https://github.com/numat/tripplite/files/7384181/Communication.Protocol.2012.pdf). It's not perfect but was enough to get me started.

**Comment by tomammon** [comment]
Thanks muchly!
