### ISSUE TITLE
Add a prometheus_exporter as an extra install to module

### ISSUE THREAD

**Issue by cooperlees** [numat/tripplite#5]
Would my prometheus_exporter, based on this module to pull data from my UPS, be accepted as an addition to this great module?

Dashboard I've built from the data collected:
<img width="935" alt="Screen Shot 2020-09-26 at 10 26 58 AM" src="https://user-images.githubusercontent.com/3005596/94346639-dd607780-ffe2-11ea-8682-3c07c3b53920.png">

**Comment by patrickfuller** [comment]
This is cool!

~~I don't think UI belongs in this repo (I'd like to keep this dedicated to simply reading the battery) but I'd be happy to link to it in the README. Let me know if you publish it and I'll add the hyperlink.~~

EDIT - I'm on board if this exporter is just exporting data in a different format. We don't even need to make it an extra. We could have a kwarg on `get` or similar.

**Comment by cooperlees** [comment]
A [prometheus exporter](https://github.com/prometheus/client_python) does just change the format, but it also runs a small http server for prometheus to come and scrape via HTTP at a period configured by the admin.

The extra dependency, [prometheus_client](https://pypi.org/project/prometheus-client/), is the main reason I thought adding as an `extra` would make sense so people who are using the library today don't pick up the extra dependency unless they actually want it.

**Comment by patrickfuller** [comment]
Agreed. Exporting to a new data format belongs here, and an added dependency belongs in an `extra` install. Happy to accept a PR here.

**Comment by cooperlees** [comment]
Thanks! Will polish it all up and make it solid before I put up the PR.
